### ISSUE TITLE
[Typescript] On query result, wrong error attribute

### ISSUE THREAD

**Issue by orblazer** [Akryum/vue-apollo#752]
Hello,
When use query and method result on vue component the object data contains `error` but the type except `errors`.

Thanks.

**Comment by dvic** [comment]
I have the same problem.

**Comment by Akryum** [comment]
I'm sorry I don't understand what the issue is, could you please be more explicit?

**Comment by orblazer** [comment]
Hello,
For explain, when we use smart query the type of error is defined from here :
https://github.com/apollographql/apollo-client/blob/1098e428a013f94281d422fbaebc4bc741a007d1/packages/apollo-client/src/core/types.ts#L24

But is result object the error is : `error`

**Comment by Akryum** [comment]
I still don't understand, could you please provide some examples? Thanks!

**Comment by orblazer** [comment]
Im little stupid because i have already make that issue in the `problem 2` on https://github.com/Akryum/vue-apollo/issues/605

**Comment by Akryum** [comment]
Is it fixed with the new types in latest versions?

**Comment by dvic** [comment]
@Akryum it's about the object passed into the `result()` callback: its type is `ApolloQueryResult<T>` but the problem is that the object received in this callback does not satisfy this interface. The `errors` field is missing and instead the field `error` (singular) is passed. I don't recall if the type is correct of this field (`GraphQLError`). I'll check with the latest RC and let you know.

**Comment by dvic** [comment]
@Akryum I can confirm this problem still exists with rc7, there is only an `error` field (instead of the `errors?: ReadonlyArray<GraphQLError>` field from `ApolloQueryResult`

**Comment by Akryum** [comment]
vue-apollo pass the `result` object from Apollo Client directly, so this is an issue with it rather than vue-apollo.
